name: openhack
dependencies:
- python=3.5.2=0
# - vs2015_runtime=14.0.25420=0
- pip:
  - numpy==1.14.0
  - opencv-python==3.4.0.12
  - matplotlib==2.1.2
  - scipy==1.0.0
  - scikit-learn==0.19.1
  - pandas==0.22.0
  - pillow

